name: Issue Tree

on:
  workflow_dispatch:
  issues:
    types: [
      opened,
      edited,
      deleted,
      closed,
      reopened,
      labeled,
    ]

concurrency:
  group: single
  cancel-in-progress: true

jobs:
  issue_tree:
    runs-on: ubuntu-latest
    name: Issue dependencies tree
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3
      - name: Draw Tree on epic
        id: draw-tree-on-epic
        uses: k-nasa/gid@main
        with:
          label: 'epic'
          github_token: ${{ secrets.ACCESS_TOKEN }}