run-name: Maven product creation
on:
  repository_dispatch: # To support manual trigger.
  push:
  pull_request: 
    branches: [main, /*main, /*-E-*]
    types: [opened, synchronize]


jobs:
  maven-build:
    runs-on: ubuntu-latest
    steps:
      - id: checkout-repo
        name: Checkout repository
        uses: actions/checkout@v4
        
      - id: setup-java
        name: Setup Java 
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 1.8.0.392+8     
                
      - id: run-mvn-pkg
        name: Run maven
        run: mvn package

      - id: commit-binary-artifact
        name: Commit binary artifact
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actor
          message: Mevan package from github action triggred by- @${{ github.actor }}

      - id: handle-failure-0
        name: The job has failed
        if: always() && !${{ success() }}
        uses: dkershner6/switch-case-action@v1
        with:
          default: "NaN"
          conditionals-with-values: |
            ${{ steps.checkout-repo.outcome != 'success' }} => checkout-repo
            ${{ steps.setup-java.outcome != 'success' }} => setup-java
            ${{ steps.run-mvn-pkg.outcome != 'success' }} => run-mvn-pkg
            ${{ steps.commit-binary-artifact.outcome != 'success' }} => commit-binary-artifact
            
      - id: handle-failure-1
        if: always() && !${{ success() }}
        run: echo The job has failed at step - ${{ steps.handle-failure-0.outputs.value }}

      - id: handle-success
        name: 

