run-name: Maven product creation
on:
  repository_dispatch: # To support manual trigger.
  push:
  pull_request: 
    branches: [main, /*main, /*-E-*]
    types: [opened, synchronize]


jobs:
  maven-build:
    runs-on: ubuntu-latest
    env:
      lastExecutedStep: nan
    steps:
      - id: checkout-repo
        env:
            lastExecutedStep: checkout-repo
        name: Checkout repository
        uses: actions/checkout@v4
        
      - id: setup-java
        env:
          lastExecutedStep: setup-java
        name: Setup Java 
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 1.8.0.392+8     
                
      - id: run-mvn-pkg
        env:
          lastExecutedStep: run-mvn-pkg
        name: Run maven
        run: mvn package

      - id: commit-binary-artifact
        env:
          lastExecutedStep: commit-binary-artifact
        name: Commit binary artifact
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actor
          message: Mevan package from github action triggred by- @${{ github.actor }}

      - id: handle-failure
        name: The job has failed
        if: always()
        run: echo Workflow failed at step - ${{ env.lastExecutedStep }}


