run-name: Maven product creation
on:
  repository_dispatch: # To support manual trigger.
  push:
    branches: [development, '*-E-*']
  pull_request: 
    branches: [development, '*-E-*'] 
    types: [opened, synchronize]

jobs:
  maven-build-pkg-creation:
    name: maven build by user - ${{ github.actor }} and event - ${{ github.event_name }} 
    runs-on: ubuntu-latest
    steps:
      - id: checkout-repo
        name: Checkout repository
        uses: actions/checkout@v4

      - id: setup-java
        name: Setup Java 
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 1.8.0.392+8     
        
      - id: run-mvn-pkg
        name: Run maven
        run: mvn package
        
      - id: commit-binary-artifact
        name: Commit binary artifact
        if: github.event_name == 'push' && github.ref_name == 'development'
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actor
          message: Mevan package from github action- ${{ github.run_number }} triggred by- @${{ github.actor }}
        
      - id: create-pr-to-test
        name: Create pull request to test branch
        if: github.event_name == 'push' && github.ref_name == 'development'
        run: echo TO-DO :Create pull request to test branch
        # env: 
          # GH_TOKEN: {{ secrets.ACCESS_TOKEN }}
        # run: gh pr create |
          # --base test --head development |
          # --fill --label test --project Arc-i-Tech-website

      - id: add-comment-to-pr
        name: Add Comment to pull request - ${{ github.event.number }}
        if: github.event_name == 'pull_request'
        run: echo TO-DO :Add comment to pull request - ${{ github.event.number }}

      - id: handle-failure-pr-0
        name: Pull request - PR:${{ github.event.number }}, base branch:'development'
        if: failure() && github.event_name == 'pull_request' && github.base_ref == 'development'
        run: echo Add comment to pull request

      - id: handle-failure-push-0
        name: Push - base branch:'development'
        if: failure() && github.event_name == 'push' && github.ref_name == 'development'
        run: echo create issue

      - id: handle-failure-pr-1
        name: Pull request - PR:${{ github.event.number }}, base branch:'*-E-*' (EPIC)
        if: failure() && github.event_name == 'pull_request' && contains(github.base_ref, '-E-')
        run: echo Add comment to pull request

      - id: handle-failure-push-1
        name: Push - base branch:'*-E-*' (EPIC)
        if: failure() && github.event_name == 'push' && contains(github.ref_name, '-E-')
        run: echo create issue

      - id: handle-failure-0
        name: Find failed step
        if: failure()
        uses: dkershner6/switch-case-action@v1
        with:
          default: "NaN"
          conditionals-with-values: |
            ${{ steps.checkout-repo.outcome != 'success' && steps.checkout-repo.outcome != 'skipped' }} => checkout-repo
            ${{ steps.setup-java.outcome != 'success'  && steps.setup-java.outcome != 'skipped' }} => setup-java
            ${{ steps.run-mvn-pkg.outcome != 'success' && steps.run-mvn-pkg.outcome != 'skipped' }} => run-mvn-pkg
            ${{ steps.commit-binary-artifact.outcome != 'success' && steps.commit-binary-artifact.outcome != 'skipped' }} => commit-binary-artifact
            ${{ steps.create-pr-to-test.outcome != 'success' && steps.create-pr-to-test.outcome != 'skipped' }} => create-pr-to-test
            ${{ steps.add-comment-to-pr.outcome != 'success' && steps.add-comment-to-pr.outcome != 'skipped' }} => add-comment-to-pr
            ${{ steps.handle-failure-pr-0.outcome != 'success' && steps.handle-failure-pr-0.outcome != 'skipped' }} => handle-failure-pr-0
            ${{ steps.handle-failure-push-0.outcome != 'success' && steps.handle-failure-push-0.outcome != 'skipped' }} => handle-failure-push-0
            ${{ steps.handle-failure-pr-1.outcome != 'success' && steps.handle-failure-pr-0.outcome != 'skipped' }} => handle-failure-pr-1
            ${{ steps.handle-failure-push-1.outcome != 'success' && steps.handle-failure-push-1.outcome != 'skipped' }} => handle-failure-pr-1

      - id: handle-failure-1
        name: Failed step info
        if: failure() 
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Test comment for failure!\nThe job has failed at step - ${{ steps.handle-failure-0.outputs.value }}'
            })

      - id: success-message
        name: Success message
        if: success()
        run: echo Action completed successfully.