run-name: Maven product creation
on:
  repository_dispatch: # To support manual trigger.
  push:
  pull_request: 
    branches: [development, /*-E-*]
    types: [opened, synchronize]


jobs:
  maven-build:
    runs-on: ubuntu-latest
    steps:
      - id: checkout-repo
        name: Checkout repository
        uses: actions/checkout@v4
        
      - id: setup-java
        name: Setup Java 
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8.0.392+8     
                
      - id: run-mvn-pkg
        name: Run maven
        run: mvn package

      - id: print-reference
        name: Print reference
        run: echo ${{ github.ref }}
      
      - id: print-event-name:
        name: Print event name
        run: echo ${{ github.event_name }}


