run-name: Maven- product creation
on:
  push:
    branches: 
    - 94-cf-maven-build-workflow

  pull_request: 
    branches: 
    - main
    - *main
    
jobs:
  maven-build:
    runs-on: ubuntu-latest
    env:
      failedStep: NaN
    steps:
      - id: checkout-repo
        name: Checkout repository
        uses: actions/checkout@v4

      - id: setup-java
        name: Setup Java 
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 1.8.0.392+8
        continue-on-error: true
        env:
          failedStep: setup-java
           
      - id: run-mvn-pkg
        name: Run maven
        run: mvn package

      - id: commit-binary-artifact
        name: Commit binary artifact
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actor
          message: Mevan package from github action triggred by- @${{ github.actor }}

      - id: handle-failure
        name: The job has failed
        if: ${{ failure() }}
        run: echo Workflow failed at step - ${{ env.failedStep }}


