run-name: Project automate

on:
  issues:
    types: [labeled, unlabeled, assigned, unassigned]

  pull_request:
    types: [reopened, ready_for_review, converted_to_draft, closed]

jobs:
  check-valid-run:
    if: ( !startsWith(github.triggering_actor, 'serv') && !endsWith(github.triggering_actor, 'cat') )
    runs-on: ubuntu-latest

    outputs:
      OPTION: ${{ steps.check-run.outputs.OPTION }}
      LABELS: ${{ steps.check-run.outputs.LABELS }}
      COMMENT: ${{ steps.check-run.outputs.COMMENT }}
      NUM: ${{ steps.check-run.outputs.NUM }}
      type: ${{ steps.check-run.outputs.type }}
      result: ${{ steps.job-result.outputs.result }}

    steps:
    - name: Action info
      id: action-info
      uses: actions/github-script@v7
      with: 
        script:
          console.log("Triggering actor:" + "${{ github.triggering_actor }}")

          if( "${{ github.event_name }}" == "issues" ) {
            console.log('Issue number:' + '${{ github.event.issue.number }}')
          }
          else if( "${{ github.event_name }}" == "pull_request" ) {
            console.log('PullReuqest number:' + '${{ github.event.number }}')
          }

    - name: Check run
      id: check-run
      uses: actions/github-script@v7
      with:
        script: |
          if( '${{ github.event.issue.state }}' == 'closed') {
            console.log("Automation only works for OPEN issues.")
            return false
          }
          // Workflow should run for below labels 
          const eventLabels = ["epic", "accepted", "started-working"]
          if( "${{github.event.action }}" == "labeled" || "${{github.event.action }}" == "unlabeled" ) {
            if( !eventLabels.includes("${{ github.event.label.name}}") ){
              console.log("Workflow is only applicable for below issue labels:\n" + eventLabels)
              return false
            }
          }

          // Certain label actions must be from assignee.
          const labels = ${{ toJSON(github.event.issue.labels.*.name) }}
          const assignees = ${{ toJSON(github.event.issue.assignees.*.login) }}
          if( "${{ github.event.label.name}}" == 'started-working') {
            if( "${{ github.event.action }}" == 'labeled' ) {
              // 1. Labeler must be an issue owner (issue assigned to)
              // 2. Without an assignee cannot be labeled
              if( assignees.length <= 0 || !assignees.includes("${{ github.triggering_actor }}") ) {
                core.setOutput('OPTION', 'remove')
                core.setOutput('LABELS', '${{ github.event.label.name}}')
                core.setOutput('COMMENT', 'Only assignees are allowed to add label: `${{ github.event.label.name}}`!<br>@${{ github.triggering_actor }} please assign issue to someone or ask assignee to add label.')
                console.log("Only assignees are allowed to add label: `started-working`!")
                return false
              }
            }
            else if( "${{ github.event.action }}" == 'unlabeled' ) {
              // 3. Only the assignee or ajayg2808 can remove label
              assignees.push('ajayg2808')
              if( assignees.length <= 0 || !assignees.includes("${{ github.triggering_actor }}") ) {
                core.setOutput('OPTION', 'add')
                core.setOutput('LABELS', '${{ github.event.label.name}}')
                core.setOutput('COMMENT', "Only assignee or admin are allowed to remove label: `${{ github.event.label.name}}`!<br>@${{ github.triggering_actor }} please ask assigne or admin to remove label.")
                console.log("Only assignees are allowed to remove label: `started-working`!")
                return false
              }
            }
          }

          core.setOutput('COMMENT', "")
          
          // TODO: Check PR constraints


          if( "${{ github.event_name }}" == 'issues' ) {
            core.setOutput('NUM', ${{ github.event.issue.number }})
            core.setOutput('type', 'Issue')
          }
          else if( "${{ github.event_name }}" == 'pull_request' ) {
            core.setOutput('NUM', ${{ github.event.number }})
            core.setOutput('type', 'PullReuqest')
          }

    - name: Job result
      id: job-result
      uses: actions/github-script@v7
      with: 
        script: |
          const stepsResult = ${{ toJSON(steps.*.outputs.result) }}
          if( stepsResult.includes('false') ) {
            return false
          }

  get-details:
    needs: check-valid-run
    if: needs.check-valid-run.outputs.result != 'false'
    runs-on: ubuntu-latest

    outputs:
      NUM: ${{ needs.check-valid-run.outputs.NUM }}
      type: ${{ needs.check-valid-run.outputs.type }}
      ids: ${{ steps.get-required-ids.outputs.ids }}
      PRJ: ${{ steps.fetch-prj-details.outputs.PRJ }}
      result: ${{ steps.job-result.outputs.result }}

    steps:
    - name: Get reuired IDs
      id: get-required-ids
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.ACCESS_TOKEN }}
        script: |
          // Fetch data for github project
          const resp = await github.graphql(`query getOrgProjRepoId {
            repository(owner:"${{ github.repository_owner }}", name:"${{ github.event.repository.name }}") {
              id
              issueOrPullRequest(number: ${{ needs.check-valid-run.outputs.NUM }}) {
                __typename
                ... on Issue {
                  id
                  projectsV2 {
                    totalCount
                  }
                }
                ... on PullRequest {
                  id
                }
              }
            },
            organization(login:"${{ github.repository_owner }}") {
              id
              projectsV2(first: 10) {
                nodes {
                  title,
                  id
                }
              }
            }
          }`)

          // Find project number and id from project name
          const prj = resp.organization.projectsV2.nodes.filter((node) => node.title == "${{ vars.MAIN_PRJ }}")
          if( prj.length == 0 ) {
            console.log("No projects found with name: ${{ vars.MAIN_PRJ }}")
            return false
          } 

          const IDs = {
            'REPO_ID': resp.repository.id,
            'PRJ_ID': prj[0].id,
            'ORG_ID': resp.organization.id,
            'I_PR_ID': resp.repository.issueOrPullRequest.id
          }
          
          core.setOutput('PRJ_ID', prj[0].id)
          core.setOutput('ids', JSON.stringify(IDs))

          if( resp.repository.issueOrPullRequest.__typename == 'Issue' ) {
            if( resp.repository.issueOrPullRequest.projectsV2.totalCount <= 0 ) {
              console.log("${{ needs.check-valid-run.outputs.type }}: ${{ needs.check-valid-run.outputs.NUM }} not associate with any github project.")
              return false
            }
          }

    - name: Fetch project details
      id: fetch-prj-details
      if: steps.get-required-ids.outputs.result != 'false'
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.ACCESS_TOKEN }}
        script: |
          const getPrjFields = await github.graphql(`query getPrjFields {
            node(id:"${{ steps.get-required-ids.outputs.PRJ_ID }}") {
              ... on ProjectV2 {
                id
                fields(first: 20) {
                  totalCount
                  nodes {
                    ... on ProjectV2Field {
                      id
                      name
                    }
                    ... on ProjectV2SingleSelectField {
                      id
                      name
                      options {
                        id
                        name
                      }
                    }
                    ... on ProjectV2IterationField {
                      id
                      name
                      configuration {
                        iterations {
                          id
                          title
                        }
                      }
                    }
                  }
                }
              }
            }
          }`)
          console.log(JSON.stringify(getPrjFields))
          core.setOutput('PRJ', JSON.stringify(getPrjFields.node))

    - name: Job result
      id: job-result
      uses: actions/github-script@v7
      with: 
        script: |
          const stepsResult = ${{ toJSON(steps.*.outputs.result) }}
          if( stepsResult.includes('false') ) {
            return false
          }

  issue-automation:
    needs: get-details
    if: needs.get-details.outputs.result != 'false' && github.event_name == 'issues'
    name: Issue automation
    runs-on: ubuntu-latest

    outputs:
      OPTION: ${{ steps.find-target-status.outputs.OPTION }}
      LABELS: ${{ steps.find-target-status.outputs.LABELS }}
      OPTION_NODE: ${{ steps.find-target-status.outputs.OPTION_NODE }}
      FIELD_ID: ${{ steps.find-target-status.outputs.FIELD_ID }}
      UPDATE_STATUS: ${{ steps.find-target-status.outputs.UPDATE_STATUS }}
      ITEM: ${{ steps.find-item.outputs.ITEM }}
      PRJ: ${{ needs.get-details.outputs.PRJ }}
      ids: ${{ needs.get-details.outputs.ids }}
      result: ${{ steps.job-result.outputs.result }}
      
    steps:
    - name: Find ITEM
      id: find-item
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.ACCESS_TOKEN }}
        script: |
          const vars = ${{ needs.get-details.outputs.ids }}

          var isFound = false
          var isOver = false
          vars.cursor = ""
          var itemNodes = []

          while(isFound == false && isOver == false) {
            const getItemIdResp = await github.graphql(`query getItemID($PRJ_ID: ID!, $cursor: String!) {
              node(id:$PRJ_ID) {
                ... on ProjectV2 {
                  id
                  items(first: 10, after:$cursor, orderBy: {
                    field:POSITION,
                    direction:DESC
                  }) {
                    nodes {
                      id
                      fieldValueByName(name:"Status") {
                        ... on ProjectV2ItemFieldSingleSelectValue {
                          id
                          name
                        }
                      }
                      content {
                        __typename
                        ... on Issue {
                          number
                          title
                          state
                        }
                      }
                    }
                    pageInfo {
                      endCursor
                      hasNextPage
                    }
                  }
                }
              }
            }`, vars)

            itemNodes = getItemIdResp.node.items.nodes.filter((node) => node.content.__typename == '${{ needs.get-details.outputs.type }}' && node.content.number === ${{ needs.get-details.outputs.NUM }})

            if( itemNodes.length > 0 ) {
              isFound = true
              break
            }
            
            if( getItemIdResp.node.items.pageInfo.hasNextPage ) {
              vars.cursor = getItemIdResp.node.items.pageInfo.endCursor
            }
            else {
              isOver = true
              break;
            }
          }

          if( isFound == true) {
            core.setOutput('ITEM', JSON.stringify(itemNodes[0]))
            return true
          }
          console.log("${{ needs.get-details.outputs.type }}: ${{ needs.get-details.outputs.NUM }} is not associated with GitHub project: ${{ vars.MAIN_PRJ }}")
          return false

    - name: Find target Status
      id: find-target-status
      if: github.event.action != 'opened' && github.event.action != 'reopened'
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.ACCESS_TOKEN }}
        script: |
          const item = ${{ steps.find-item.outputs.ITEM }}

          const labels = ${{ toJSON(github.event.issue.labels.*.name) }}
          const assignees = ${{ toJSON(github.event.issue.assignees) }}

          var targetOptionVal = ""
          if( labels.includes('epic') ) {
            targetOptionVal = ":file_cabinet: Epic"
            if( labels.includes("started-working") ) {
              core.setOutput('OPTION', 'remove')
              core.setOutput('LABELS', 'started-working')
            }
          }
          else if( assignees.length > 0 || "${{ github.event.action }}" == 'assigned') { 
            if( labels.includes('started-working') || ( "${{ github.event.action }}" == 'labeled' && "${{ github.event.label.name }}" == 'started-working' )) {
              targetOptionVal = "🏗 In progress"
            }
            else {
              targetOptionVal = "🔖 Sprint Backlog"
            }
          }
          else if( "${{ github.event.action }}" == 'labeled' ) {
            if( "${{ github.event.label.name }}" == 'epic' ) {
              targetOptionVal = ":file_cabinet: Epic"
              if( labels.includes("started-working") ) {
                core.setOutput('OPTION', 'remove')
                core.setOutput('LABELS', 'started-working')
              }
            }
            else if( "${{ github.event.label.name }}" == 'accepted' ) {
              targetOptionVal = "📋 Product Backlog"
            }
          }
          else if( "${{ github.event.action }}" == 'unlabeled' ) {
            if( "${{ github.event.label.name }}" == "accepted" ) {
              targetOptionVal = "🆕 New"
            }
            else if( '${{ github.event.label.name }}' == 'started-working' ) {
              if( labels.includes("accepted") ) {
                targetOptionVal = "📋 Product Backlog"
              }
              else {
                targetOptionVal = "🆕 New"
              }
            }
          }
          else if( "${{ github.event.action }}" == 'unassigned' ) {
            if( labels.includes("accepted") ) {
              targetOptionVal = "📋 Product Backlog"
            }
            else {
              targetOptionVal = "🆕 New"
            }
            if( labels.includes("started-working") ) {
              if( assignees.length <= 0 ) {
                core.setOutput('OPTION', 'remove')
                core.setOutput('LABELS', 'started-working')
              }
            }
          }
          else {
            console.log("No valid target value found for Event: ${{ github.event.action}}")
            return false
          } 
          if( targetOptionVal == item.fieldValueByName.name ) {
            console.log("Target Status value and current status value are same: " + targetOptionVal)
            return false
          }

          const prj = ${{ needs.get-details.outputs.PRJ }}
          const fieldNode = prj.fields.nodes.filter((node) => node.name.toUpperCase() == 'status'.toUpperCase())
          const optionNode = fieldNode[0].options.filter((option) => option.name == targetOptionVal )

          core.setOutput("OPTION_NODE", JSON.stringify(optionNode))
          core.setOutput("FIELD_ID", fieldNode[0].id)
          core.setOutput("UPDATE_STATUS", "true")

          console.log("Target Status value: " + targetOptionVal)

    - name: Job result
      id: job-result
      uses: actions/github-script@v7
      with: 
        script: |
          const stepsResult = ${{ toJSON(steps.*.outputs.result) }}
          if( stepsResult.includes('false') ) {
            return false
          }
  
  pr-automation:
    needs: get-details
    if: needs.get-details.outputs.result != 'false' && github.event_name == 'pull_request' 
    runs-on: ubuntu-latest

    outputs:
      PRJ: ${{ needs.get-details.outputs.PRJ }}
      ids: ${{ needs.get-details.outputs.ids }}
      COMMENT: ${{ steps.check-associated-issues.outputs.COMMENT }}
      COMMENT1: ${{ steps.reopened.outputs.COMMENT }}
      OPTION_NODE: ${{ steps.find-ref-issues-target-status.outputs.OPTION_NODE }}
      FIELD_ID: ${{ steps.find-ref-issues-target-status.outputs.FIELD_ID }}
      UPDATE_STATUS: ${{ steps.find-ref-issues-target-status.outputs.UPDATE_STATUS }}
      ITEMS: ${{ steps.get-open-ref-items.outputs.ITEMS }}
      COMMENT2: ${{ steps.get-open-ref-items.outputs.COMMENT }}
      result: ${{ steps.job-result.outputs.result }}

    steps:
    - name: Check associated issues
      id: check-associated-issues
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.ACCESS_TOKEN }}
        script: |
          const vars = ${{ needs.get-details.outputs.ids }}
          const resp = await github.graphql(`query getClosingIssueIDs($I_PR_ID: ID!) {
            node(id: $I_PR_ID ) {
              ... on PullRequest {
                id
                title
                number
                closingIssuesReferences(first: 10) {
                  nodes {
                    __typename
                    id
                    number
                    title
                    state
                  }
                }
                assignees(first:10) {
                  nodes {
                    name
                    login
                  }
                }
              }
            }
          }`, vars)

          var closingIssues = resp.node.closingIssuesReferences.nodes;
          if( closingIssues.length <= 0 ) {
            if( "${{ github.event.action }}" != "closed" ){
              core.setOutput('COMMENT', "This pull request does not reference any closing issues.</br>Link reference closing issues to proceed further with this PR.");
            }
            console.log("pull request: " + resp.node.number +" does not reference any closing issues.")
            return false
          }
          console.log("Pull Request is associate with below github issues.");
          for(var i = 0; i < closingIssues.length; i++) {
            console.log(closingIssues[i].number + ":" + closingIssues[i].state + ":" + closingIssues[i].title)
          }
          core.setOutput('COMMENT', '')
          core.setOutput("CLOSING_ISSUES", JSON.stringify(closingIssues))
          core.setOutput("PR_ASSIGNEES", JSON.stringify(resp.node.assignees.nodes))
          return true
          
    - name: Reopened
      id: reopened
      if: github.event.action == 'reopened' && steps.check-associated-issues.outputs.result != 'false'
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.ACCESS_TOKEN }}
        script: |
          const closingIssues = ${{ steps.check-associated-issues.outputs.CLOSING_ISSUES }}
          var closedRefIssues = closedRefIssues.filter((issue) => issue.state != "OPEN")
          var cmt = ""
          for(let i of closedRefIssues) {
            cmt += "<br>#" + i.number
          }
          if( closedRefIssues.length == closingIssues.length ) {
            core.setOutput('COMMENT', "Reference issue of this pull request are not in `OPEN` state:" + cmt + "<br>Is this pull request is still valid?")
            return false
          }
          else if( closedRefIssues.length > 0) {
            core.setOutput('COMMENT', "Some of reference issue of this pull request are not in `OPEN` state:" + cmt + "<br>Is this pull request is still valid?")
            return true;
          }
          core.setOutput('COMMENT', "")
          return true

    - name: Find reference issues target Status
      id: find-ref-issues-target-status
      if: steps.check-associated-issues.outputs.result != 'false'
      uses: actions/github-script@v7
      with:
        script: |
          const reviewerTeams = ${{ toJSON(github.event.pull_request.requested_teams.*.name) }}
          const reviewers = ${{ toJSON(github.event.pull_request.requested_reviewers) }}
          
          var targetOptionVal = ""
          if( ${{ github.event.pull_request.draft }} || "${{ github.event.action }}" == "converted_to_draft") {
            targetOptionVal = "🏗 In progress"
          }
          else if( ( "${{ github.event.action }}" == "ready_for_review" || reviewers.length > 0 || reviewerTeams.length > 0 ) && "${{ github.event.action }}" != "closed" ) {
            targetOptionVal = "👀 In review"
          }
          else {
            console.log("No valid target value found for Event: ${{ github.event.action}}")
            return false
          } 
          const prj = ${{ needs.get-details.outputs.PRJ }}
          const fieldNode = prj.fields.nodes.filter((node) => node.name.toUpperCase() == 'status'.toUpperCase())
          const optionNode = fieldNode[0].options.filter((option) => option.name == targetOptionVal )

          core.setOutput("OPTION_NODE", JSON.stringify(optionNode))
          core.setOutput("FIELD_ID", fieldNode[0].id)
          core.setOutput("UPDATE_STATUS", "true")

          console.log("Target Status value: " + targetOptionVal + " for OPEN reference issue closing by Pull Request: " + ${{ github.event.number }})

    - name: Get open reference items
      id: get-open-ref-items
      if: steps.check-associated-issues.outputs.result != 'false'
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.ACCESS_TOKEN }}
        script: |
          const closingIssues = ${{ steps.check-associated-issues.outputs.CLOSING_ISSUES }}
          var openRefIssues = closingIssues.filter((issue) => issue.state == "OPEN")
          var openRefIssueNos = openRefIssues.map((issue) => issue.number )

          const vars = ${{ needs.get-details.outputs.ids }}

          var isFoundAll = false
          var isOver = false
          vars.cursor = ""
          var itemNodes = []

          while(isFoundAll == false && isOver == false) {
            const getItemIdResp = await github.graphql(`query getItemID($PRJ_ID: ID!, $cursor: String!) {
              node(id:$PRJ_ID) {
                ... on ProjectV2 {
                  id
                  items(first: 10, after:$cursor, orderBy: {
                    field:POSITION,
                    direction:DESC
                  }) {
                    nodes {
                      id
                      fieldValueByName(name:"Status") {
                        ... on ProjectV2ItemFieldSingleSelectValue {
                          id
                          name
                        }
                      }
                      content {
                        __typename
                        ... on Issue {
                          number
                          title
                        }
                      }
                    }
                    pageInfo {
                      endCursor
                      hasNextPage
                    }
                  }
                }
              }
            }`, vars)

            const filteredNodes = getItemIdResp.node.items.nodes.filter((node) => node.content.__typename == 'Issue' && openRefIssueNos.includes(node.content.number) )
            itemNodes.push(...filteredNodes)

            if( itemNodes.length == openRefIssueNos.length ) {
              isFoundAll = true
              break
            }
            
            if( getItemIdResp.node.items.pageInfo.hasNextPage ) {
              vars.cursor = getItemIdResp.node.items.pageInfo.endCursor
            }
            else {
              isOver = true
              break;
            }
          }
          
          if( isFoundAll == true && itemNodes.length != 0) {
            console.log("All issue found in ${{ vars.MAIN_PRJ }} project.")
          }
          else if ( itemNodes.length != 0) {
            const notFoundIssues = itemNodes.filter((node) => !openRefIssueNos.includes(node.content.number))
            var cmt = ""
            for(let i of notFoundIssues) {
              cmt += "<br>#" + i.content.number
            }
            core.setOutput('COMMENT', "Below issues do not belong to ${{ vars.MAIN_PRJ }}" + cmt);
          }
          else {
            console.log("No reference issue belong to ${{ vars.MAIN_PRJ }}")
            return false
          }
          core.setOutput('ITEMS', JSON.stringify(itemNodes))
          core.setOutput('COMMENT', "");
          core.setOutput('openRefIssueNos', JSON.stringify(openRefIssueNos));
          return true

    - name: Check and assign PR
      id: check-and-assign-pr
      if: steps.check-associated-issues.outputs.result != 'false'
      uses: actions/github-script@v7
      with:
        script:
          console.log("TODO:- Write a step to assign PR")

    - name: Close reference issues
      id: close-ref-issues
      if: steps.check-associated-issues.outputs.result != 'false' && github.event.action == 'closed'
      env:
        GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      shell: bash
      run : |
        for i in ${{ steps.get-open-ref-items.outputs.openRefIssueNos }} ;
        do
          echo $i
        done

    - name: Job result
      id: job-result
      uses: actions/github-script@v7
      with: 
        script: |
          const stepsResult = ${{ toJSON(steps.*.outputs.result) }}
          if( stepsResult.includes('false') ) {
            return false
          }

  update-status-sprint:
    needs: [issue-automation, pr-automation]
    if: always() && ( needs.issue-automation.outputs.result != 'false' || needs.pr-automation.outputs.result != 'false' ) && ( ( needs.issue-automation.result == 'success' && needs.pr-automation.result == 'skipped' ) || ( needs.issue-automation.result == 'skipped' && needs.pr-automation.result == 'success' ) )
    runs-on: ubuntu-latest

    outputs:
      result: ${{ steps.job-result.outputs.result }}

    steps:
    - name: Collect inputs
      id: collect-inputs
      uses: actions/github-script@v7
      with:
        script: |
          if( '${{ github.event_name }}' == 'issues' ) {
            core.setOutput('OPTION_NODE', '${{ needs.issue-automation.outputs.OPTION_NODE }}')
            core.setOutput('FIELD_ID', '${{ needs.issue-automation.outputs.FIELD_ID }}')
            core.setOutput('UPDATE_STATUS', '${{ needs.issue-automation.outputs.UPDATE_STATUS }}')
            var ITEMS = [ ${{ needs.issue-automation.outputs.ITEM }} ]
            core.setOutput('ITEMS', JSON.stringify(ITEMS))
            core.setOutput('PRJ', '${{ needs.issue-automation.outputs.PRJ }}')
            core.setOutput('ids', '${{ needs.issue-automation.outputs.ids }}')
          }
          else if( '${{ github.event_name }}' == 'pull_request' ) {
            core.setOutput('OPTION_NODE', '${{ needs.pr-automation.outputs.OPTION_NODE }}')
            core.setOutput('FIELD_ID', '${{ needs.pr-automation.outputs.FIELD_ID }}')
            core.setOutput('UPDATE_STATUS', '${{ needs.pr-automation.outputs.UPDATE_STATUS }}')
            core.setOutput('ITEMS', '${{ needs.pr-automation.outputs.ITEMS }}')
            core.setOutput('PRJ', '${{ needs.pr-automation.outputs.PRJ }}')
            core.setOutput('ids', '${{ needs.pr-automation.outputs.ids }}')
          }
          else {
            return false
          }

    - name: Update Status
      id: update-status
      if: steps.collect-inputs.outputs.result != 'false' && steps.collect-inputs.outputs.UPDATE_STATUS == 'true'
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.ACCESS_TOKEN }}
        script: |
          const optionNode = ${{ steps.collect-inputs.outputs.OPTION_NODE }}
          const ITEMS = ${{ steps.collect-inputs.outputs.ITEMS }}
          const vars = ${{ steps.collect-inputs.outputs.ids }}
          vars["FIELD_ID"] = "${{ steps.collect-inputs.outputs.FIELD_ID }}"
          vars["OPTION_ID"] = optionNode[0].id
          var updateIssueStatusResp;
          for(var i=0; i < ITEMS.length; i++) {
            vars["ITEM_ID"] = ITEMS[i].id
            updateIssueStatusResp = await github.graphql(`mutation UpdateIssueStatus($ORG_ID: String!, $PRJ_ID: ID!, $ITEM_ID: ID!, $FIELD_ID: ID!, $OPTION_ID: String!) {
              updateProjectV2ItemFieldValue( input: {
                clientMutationId:$ORG_ID
                projectId:$PRJ_ID
                itemId:$ITEM_ID
                fieldId:$FIELD_ID
                value: {
                  singleSelectOptionId: $OPTION_ID
                }
              }) {
                clientMutationId
                projectV2Item {
                  id
                }
              }
            }`, vars)
            if( '${{ github.event_name }}' == 'pull_request' ) {
              if( updateIssueStatusResp.updateProjectV2ItemFieldValue.clientMutationId == vars.ORG_ID ) {
                console.log("Issue(" + ITEMS[i].content.number + ") Status changed to: " + optionNode[0].name)
              }
              else {
                console.log("Error while changing Issue: " + ITEMS[i].content.number + " status to: " + optionNode[0].name)
              }
            }
          }
          if( '${{ github.event_name }}' == 'issues' ) {
            if( updateIssueStatusResp.updateProjectV2ItemFieldValue.clientMutationId == vars.ORG_ID ) {
              console.log("Issue Status changed to: " + optionNode[0].name)
              return true
            }
            else {
              console.log("Error while changing Issue: ${{ github.event.issue.number }} status to: " + optionNode[0].name)
              return false
            }
          }

    - name: Update Sprint
      id: update-sprint
      if: steps.update-status.outputs.result != 'false' && ( github.event.action == 'assigned' || github.event.action == 'unassigned' ) && github.event_name == 'issues'
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.ACCESS_TOKEN }}
        script: |
          const prj = ${{ steps.collect-inputs.outputs.PRJ }}
          const fieldNode = prj.fields.nodes.filter((node) => node.name.toUpperCase() == "🏃 Sprint".toUpperCase())
          const vars = ${{ steps.collect-inputs.outputs.ids }}
          const ITEM = ${{ steps.collect-inputs.outputs.ITEM }}
          vars["FIELD_ID"] = fieldNode[0].id
          vars["ITR_ID"] = fieldNode[0].configuration.iterations[0].id
          vars["ITEM_ID"] = ITEM.id
          var q1 = ""
          var q2 = ""
          var q3 = ""
          if( "${{ github.event.action }}" == 'assigned' ) {
            q1 = ", $ITR_ID: String!"
            q2 = ` value: {
                  iterationId: $ITR_ID
                }`
            q3 = "updateProjectV2ItemFieldValue"
          }
          else {
            q3 = "clearProjectV2ItemFieldValue"
          }
          var query = "mutation UpdateSprint($ORG_ID: String!, $PRJ_ID: ID!, $ITEM_ID: ID!, $FIELD_ID: ID!" +
          q1 + `) {` + q3 + `(input: {
            clientMutationId: $ORG_ID
            projectId: $PRJ_ID
            itemId: $ITEM_ID
            fieldId: $FIELD_ID` + q2 + `}) {
              clientMutationId
              projectV2Item {
                id
              }
            }
          }`

          const UpdateSprintResp = await github.graphql(query, vars)

          if( UpdateSprintResp[q3].clientMutationId == vars.ORG_ID && UpdateSprintResp[q3].projectV2Item.id == vars.ITEM_ID ) {
            console.log("Sprint updated successfully")
            return true            
          }
          else {
            console.log("Unable to update sprint field")
            return false
          }
    
    - name: Job result
      id: job-result
      uses: actions/github-script@v7
      with: 
        script: |
          const stepsResult = ${{ toJSON(steps.*.outputs.result) }}
          if( stepsResult.includes('false') ) {
            return false
          }

  add-remove-label-comment:
    needs: [check-valid-run, issue-automation, pr-automation]
    if: always()
    runs-on: ubuntu-latest
    steps:
    - name: Collect labels and comments
      id: collet-labels-comments
      uses: actions/github-script@v7
      with:
        script: |
          var COMMENTS = []
          if( '${{ github.event_name }}' == 'issues' && '${{ needs.issue-automation.result }}' == 'success' ){
            core.setOutput( 'LABELS', '${{ needs.issue-automation.outputs.LABELS }}' )
            COMMENTS.push('')
            core.setOutput( 'OPTION', '${{ needs.issue-automation.outputs.OPTION }}' )
          }
          else if( '${{ github.event_name }}' == 'pull_request' ) {
            core.setOutput( 'LABELS', '' )
            COMMENTS.push('${{ needs.pr-automation.outputs.COMMENT }}')            
            COMMENTS.push('${{ needs.pr-automation.outputs.COMMENT1 }}')
            COMMENTS.push('${{ needs.pr-automation.outputs.COMMENT2 }}')
          }
          else  {
            COMMENTS.push('${{ needs.check-valid-run.outputs.COMMENT }}')
            core.setOutput( 'LABELS', '${{ needs.check-valid-run.outputs.LABELS }}' )
            core.setOutput( 'OPTION', '${{ needs.check-valid-run.outputs.OPTION }}' )
          }
          core.setOutput( 'COMMENTS', JSON.stringify(COMMENTS) )

    - name: Remove Label
      id: remove-label
      if: steps.collet-labels-comments.outputs.LABELS != ''
      uses: buildsville/add-remove-label@v2.0.1
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        labels: ${{ steps.collet-labels-comments.outputs.LABELS }}
        type: ${{ steps.collet-labels-comments.outputs.OPTION }}

    - name: Comment on Issue
      id: issue-comment
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.ACCESS_TOKEN }}
        script: |
          const COMMENTS = ${{ steps.collet-labels-comments.outputs.COMMENTS }}
          for(var i=0; i < COMMENTS.length; i++) {
            if(COMMENTS[i] != "") {
              github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: COMMENTS[i]
              })
              console.log("Commented on: " + context.issue.number)
            }
          }
